<?php

function artwork_block($op = 'list', $delta = 0) {
  $block = array();

  if ($op == "list") {
    $block = array();
    $block[0]["info"] = t('Artwork Examples');
  } else if ($op == 'view') {
    // Generate our block content
    // set up an empty string to contain the block contents

    switch($delta) {
      case "0":
        $block_content = load_workset();
        $block['subject'] = "Artwork Examples";
        $block['content'] = $block_content;
        $block['cache_mode'] = BLOCK_NOT_CACHABLE;
        break;
    }
  }

  return $block;
}

function load_workset() {
  $node = node_load(arg(1));
  //$array = array_merge($node->field_videos, $node->field_work_set_1, $node->field_work_set_2, $node->field_work_set_3, $node->field_work_set_4, $node->field_work_set_5, $node->field_work_set_6);
  $array = array_merge($node->field_videos, $node->field_portfolio);

  $images = array();
  foreach ($array as $row) {
    if (!empty($row['fid'])) {
      $thumbnail = theme('imagecache', 'profile_work', $row['filepath']);
      $images[]['data'] = l($thumbnail, $row['filepath'], array(html=>true));
    } else if (!empty($row['embed'])) {
      //$thumbnail = theme('imagecache_external', 'profile_work', $row['data']['thumbnail']['url']);
      $image_url = imagecache_external_generate_path($row['data']['thumbnail']['url'], 'profile_work');
      $thumbnail = '<img src="' . $image_url . '" alt="image description" />';
      $images[]['data'] = l($thumbnail, $row['embed'], array(html=>true));
    }
  }

  $output = theme('item_list', $images);
  return $output;
}
